import { Inter } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="bg-light">
            <body className={inter.className}>
                <div className="flex">
                    <div className="h-screen">
                        <Sidebar />
                    </div>
                    <div className="">
                        <Header />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
