import { Inter } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
// w-[calc(100vw-10rem)]

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="bg-light">
            <body className={inter.className}>
                <div className="flex flex-wrap">
                    <div className=" flex h-screen fixed z-10">
                        <Sidebar />
                    </div>
                    <div className="flex flex-col w-[calc(100vw-10rem)] h-full ml-32 mx-8 relative">
                        <Header />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
