import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="bg-light">
            <body className={inter.className}>
                <div className="grid grid-cols-6 gap-4">
                    <div className="col-span-1 ml-4 my-4">
                        <Navbar />
                    </div>
                    <div className="col-span-5 my-4">
                        <Header />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
